<?php
/**
 * Fourwallsinn_Khalti
 *
 * @category    Payment Gateway
 * @package     Fourwallsinn_Khalti
 * @author      4 Walls Innovations
 * @copyright   4 Walls Innovations (http://www.4wallsinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<div class="payflow-settings-notice">
    <strong><?= __('Getting Started') ?></strong>
    <p>Khalti is the new generation Payment Gateway, Digital Wallet and API provider for various services. We provide
        you with true Payment Gateway, where you can accepts payments from
        For Queries, feel free to call us at 9801165568 or email merchantapi@khalti.com</p>

    <button class="tablinks" id="defaultTab" onclick="openTabs(event, 'Transactions'); return false;" href="#">
        <?= __('Transactions') ?>
    </button>
    <button class="tablinks" onclick="openTabs(event, 'FAQ'); return false;" href="#"><?= __('FAQ') ?></button>
    <div id="Transactions" class="tabcontent">
        <?php if ($block->transactionDetail()) :
            $transactionDetail = $block->transactionDetail();
            ?>
            <div class="content">
                <h3><?= __('Transaction Details') ?></h3>
                <p> <?= __('Source') ?> <?= $block->escapeHtml($transactionDetail["source"]); ?></p>
                <p> <?= __('Mobile') ?> <?= $block->escapeHtml($transactionDetail["mobile"]); ?></p>
                <p><?= __('Amount') ?> <?= $block->escapeHtml($transactionDetail["amount"]); ?></p>
                <p><?= __('Fee Amount') ?> <?= $block->escapeHtml($transactionDetail["fee_amount"]); ?></p>
                <p><?= __('Date') ?> <?= $block->escapeHtml($transactionDetail["date"]); ?></p>
                <p><?= __('State') ?> <?= $block->escapeHtml($transactionDetail["state"]); ?></p>
                <?php if ($transactionDetail['refunded'] != true) : ?>
                    <a style="padding:5px;background-color:#e0e1e2"
                       onclick="confirm('Are you sure you want to refund the amount?');return true;"
                       href="<?= $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>&refund=true">
                        <?= __('Refund') ?>
                    </a>
                <?php endif ?>
                <a style="padding:5px;background-color:#e0e1e2" onclick="window.history.go(-1);return false;">
                    <?= __('Back') ?>
                </a>
            </div>
        <?php else : ?>
        <div class="content">
            <table class="table table-bordered table-hover" id="transaction_tbl" style="margin-top:20px">
                <thead>
                    <tr>
                        <th><?= __('Source') ?></th>
                        <th><?= __('Amount(Rs)') ?></th>
                        <th><?= __('Fee(Rs)') ?></th>
                        <th><?= __('Date') ?></th>
                        <th><?= __('Type') ?></th>
                        <th><?= __('State') ?></th>
                        <th><?= __('#') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getTransactions() as $transaction) : ?>
                    <tr>
                        <td><?= $block->escapeHtml($transaction['source']); ?></td>
                        <td><?= $block->escapeHtml($transaction['amount']); ?></td>
                        <td><?= $block->escapeHtml($transaction['fee']); ?></td>
                        <td><?= $block->escapeHtml($transaction['date']); ?></td>
                        <td><?= $block->escapeHtml($transaction['type']); ?></td>
                        <td><?= $block->escapeHtml($transaction['state']); ?></td>
                        <td>
                            <a href="?transaction_id=<?= $block->escapeHtml($transaction['idx']); ?>"
                               class="btn btn-primary"><?= __('View') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php endif ?>
    <div id="FAQ" class="tabcontent">
        <strong class="important-label"><?= __('FAQ') ?></strong>
        <p>
            <strong>I forgot my password. How do I reset it ?</strong><br/>
            Please visit khalti.com/recover to reset your password
        </p>
        <p>
            <strong>How do I change my password?</strong><br/>
            You can change your password from your account setting page.Click on "Change Password"
        </p>
        <p>
            <strong>Why do you need my Citizenship, Drivers License or Passport?</strong><br/>
            As per the policy for financial transactions, we need to verify your identity.
        </p>
    </div>
</div>

<script>
    document.getElementById("defaultTab").click();

    function openTabs(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

<script type="text/javascript">
    require(['jquery', 'dataTables', 'sweetAlert'], function ($) {
        $('#transaction_tbl').DataTable();
    });
</script>