<?php
/**
* Fourwallsinn_Khalti
*
* @category    Payment Gateway
* @package     Fourwallsinn_Khalti
* @author      4 Walls Innovations
* @copyright   4 Walls Innovations (http://www.4wallsinn.com)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

?>
<div class="payflow-settings-notice">
    <strong class="important-label">Instructions:</strong>
    <p>Please Enter your Merchant ID before enabling</p>
    <ul class="options-list">
    </ul>
    <p>For any problem in this Module Please Contact<a href="mailto:info@4wallsinn.com" target="_blank">info@4wallsinn.com</a></p>
    <strong class="important-label">NOTE:</strong>
    <p>This Payment Gateway Module was not made by Khalti</p>
</div>
