<?php
/**
* Fourwallsinn_Khalti
*
* @category    Payment Gateway
* @package     Fourwallsinn_Khalti
* @author      4 Walls Innovations
* @copyright   4 Walls Innovations (http://www.4wallsinn.com)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/*
?>
<div>
<table style="width: 300px; margin: 0 auto;">
  <tbody>
    <tr>
      <td colspan="2" style="text-align: center;border-bottom: 1px solid black;font-weight: bold; font-size: 13px;">
        <br />
        <img src="" style="width: 100px;" />
      </td>
    </tr>
    <tr>
      <td>
        Entidade
      </td>
      <td style="text-align: right;font-weight: bold;">
      </td>
    </tr>
    <tr>
      <td>
        Referencia
      </td>
      <td style="font-weight: bold;text-align: right;">
      </td>
    </tr>
    <tr>
      <td>
        Valor
      </td>
      <td style="font-weight: bold;text-align: right;">
      </td>
    </tr>
    <tr>
      <td colspan="2" style="text-align: center;font-weight: bold;border-top: 1px solid black; font-size: 7px;">
      </td>
    </tr>
  </tbody>
</table>
</div>
*/?>
<p>Khalti</p>