<html>
<head>
	<script src="https://khalti.com/static/khalti-checkout.js"></script>
</head>
<body>
    <!-- Place this where you need payment button -->
    <button id="payment-button">Pay with Khalti</button>
    <!-- Place this where you need payment button -->
    <!-- Paste this code anywhere in you body tag -->
    <script>
        var config = {
            // replace the publicKey with yours
            "publicKey": "test_public_key_34e29836125b4905a8eb03c92778d524",
            "productIdentity": "<?php echo $block->getOrderId();?>",
            "productName": "MusicCafeShop",
            "productUrl": "https://shop.musiccafenepal.com",
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    var token = payload.token;
                    var amount = payload.amount;
                    window.location.href = 'https://shop.musiccafenepal.com/khalti/response/response/?token='+token+'&amount='+amount;
                },
                onError (error) {
                    console.log(error);
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        //btn.onclick = function () {
            checkout.show({amount: <?php echo $block->getTotal();?>});
        //}
    </script>
    <!-- Paste this code anywhere in you body tag -->
<?php /*
<form id="khalti_redirect_form" method="POST" action="<?php echo $block->getKhaltiTestUrl();?>">
	<input type="hidden" name="pid" value="<?php echo $block->getOrderId(); ?>">
    <input type="hidden" name="tAmt" value="<?php echo $block->getTotal(); ?>">
    <input type="hidden" name="amt" value="<?php echo $block->getTotal(); ?>">
<input value="0" name="txAmt" type="hidden">
<input value="0" name="psc" type="hidden">
<input value="0" name="pdc" type="hidden">
<input value="<?php echo $block->getMerchantId();?>" name="scd" type="hidden">
<input value="https://www.olizstore.com/khalti/response/response" type="hidden" name="su">
<input value="https://www.olizstore.com/khalti/response/response" type="hidden" name="fu">
</form>
<script>
     document.getElementById('khalti_redirect_form').submit();
</script>
*/?>
</body>
</html>
